[package]
name = "bat-notif"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
cancellable-timer = "0.1.0"
color-eyre = "0.6.2"
ctrlc = "3.4.1"
dirs = "5.0.1"
notify-rust = "4.10.0"
serde = "1.0.193"
serde_json = "1.0.108"
